# Generated by Django 5.0.1 on 2024-01-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
